name: Auto Sync Upstream

on:
  schedule:
    # 每天 UTC 时间 0:00（北京时间上午 8:00）自动运行一次
    - cron: '0 0 * * *'
  # 支持在 GitHub 页面手动点击触发同步
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: main # 注意：如果原仓库默认分支是 master，请把这里的 main 改为 master

    - name: Sync upstream changes
      uses: aレ/git-sync@v2
      with:
        upstream_repo: "https://github.com/shihabal3amri/DiPlay.git"
        upstream_branch: "main" # 注意：如果原仓库主分支是 master，请改成 master
        target_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
